### ISSUE TITLE
RGA and Bilinear scaling broken in Retroarch 32bit (Void)

### ISSUE THREAD

**Issue by shoesio** [valadaa48/retroroller#148]
Turning on either RGA scaling or Bilinear filter crashes Retroarch32.

To reproduce:
Turn on bilinear filter in video settings

or

turn on RGA scaling in video settings

Retroarch 32 will crash and exit

**Comment by valadaa48** [comment]
From or chat we assume this is due a combination of spring and retroarch restarting after changing these settings? Not sure there is an easy fix.

**Comment by valadaa48** [comment]
Can we try to narrow down the scope of this issue. Are we specifically talking about retroarch32 itself crashing when switching these modes or do you merely think it's "crashing" because it restarts back to retroarch64? If it's the latter then, I'm afraid there's nothing to do at this point other than pray we get rid of 32bit cores. Also, if it's again the latter, the safest thing might be to boot into retroarch32 directly and set a per-core option so you don't need to change this stuff again.

**Comment by valadaa48** [comment]
Feel free to re-open if you still think this is an issue that can be reasonably addressed.
